name: cakewake_delivery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  get: ^4.7.2
  get_storage: ^2.1.1
  intl_phone_field: ^3.2.0
  logger: ^2.5.0
  pinput: ^5.0.1
  geocoding: ^4.0.0
  location: ^8.0.0
  csv: ^6.0.0
  image_picker: ^1.1.2
  camera: ^0.11.1
  permission_handler: ^12.0.0+1
  infinite_scroll_pagination: ^5.1.0
  socket_io_client: ^3.1.2
  google_maps_flutter: ^2.12.3
  flutter_polyline_points: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/static/Inter_18pt-Regular.ttf
    - family: Mukta
      fonts:
        - asset: assets/fonts/Mukta-Regular.ttf
        - asset: assets/fonts/Mukta-Medium.ttf
  assets:
    - assets/images/onboarding/
    - assets/images/authentication/
    - assets/images/profile/
    - assets/images/home/
    - assets/city_dataset/worldcities.csv
    - assets/map_styles/
  uses-material-design: true
